# -*- coding: utf-8 -*-
"""atv_01_iagen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18HtGNRkicivExHJDmbW_TmvHHZCpO9Ee
"""

r1 = 0
while (r1 <= 0) or (r1 >= 6):
  r1 = float(input("""-----Calculo de aumento automático-----
  Digite seu cargo:
  1) Escriturário
  2) Secretário
  3) Caixa
  4) Gerente
  5) Diretor
  """))

s1 = float(input("""Digite o valor do seu salário atual:
R$"""))

if s1 <= 0:
  print("!!!!Salário invalido!!!!")
else:
  match (r1):
    case (1):
      p1 = 0.5
      print(f"""
Parabens você recebeu um aumento de 50% que corresponde a R${s1*p1}
Seu salario como escriturário agora é equivalente a R${s1*p1+s1} bruto
""")
    case (2):
      p1 = 0.35
      print(f"""
Parabens você recebeu um aumento de 35% que corresponde a R${s1*p1}
Seu salario como secretário agora é equivalente a R${s1*p1+s1} bruto
""")
    case (3):
      p1 = 0.2
      print(f"""
Parabens você recebeu um aumento de 20% que corresponde a R${s1*p1}
Seu salario como caixa agora é equivalente a R${s1*p1+s1} bruto
""")
    case (4):
      p1 = 0.1
      print(f"""
Parabens você recebeu um aumento de 10% que corresponde a R${s1*p1}
Seu salario como gerente agora é equivalente a R${s1*p1+s1} bruto
""")
    case (5):
      print("Olá diretor, seu salário ja está acima do padrão do mercado, então você não recebera um aumento")

e1 = str(input("""Escolha qual das opções você deseja acessar
1) Imposto
2) Novo salário
3) Classificação
"""))

match(e1):
  case('1'):
    s1 = float(input("""Digite o salário para o calculo do imposto respectivo:
R$"""))
    if s1 <= 0:
      print("Valor de salário invalido")
    elif s1 < 1500:
      print(f"""Respeitando o valor desse salário o imposto corresponde a 5% do seu valor bruto
O valor do imposto corresponde a R${s1*0.05}""")
    elif s1 <= 1850:
      print(f"""Respeitando o valor desse salário o imposto corresponde a 10% do seu valor bruto
O valor do imposto corresponde a R${s1*0.1}""")
    else:
      print(f"""Respeitando o valor desse salário o imposto corresponde a 15% do seu valor bruto
O valor do imposto corresponde a R${s1*0.15}""")

  case('2'):
    s1 = float(input("""Digite o salário para o calculo do imposto respectivo:
R$"""))
    if s1 <= 0:
      print("Valor de salário invalido")
    elif s1 < 1450:
      print(f"""
Parabens você recebeu um aumento de R$100,00
Seu novo salário corresponde a R${s1+100}
""")
    elif s1 < 1750:
      print(f"""
Parabens você recebeu um aumento de R$75,00
Seu novo salário corresponde a R${s1+75}
""")
    elif s1 <= 2500:
      print(f"""
Parabens você recebeu um aumento de R$50,00
Seu novo salário corresponde a R${s1+50}
""")
    else:
      print(f"""
Parabens você recebeu um aumento de R$25,00
Seu novo salário corresponde a R${s1+25}
""")

  case('3'):
    s1 = float(input("""Digite o salário para o calculo do imposto respectivo:
R$"""))
    if s1 <= 0:
      print("Valor de salário invalido")
    elif s1 <= 1700:
      print("""!!!!Atenção!!!!
Você está mal remunerado entre em contato com seu superior para negociar sua situação""")
    else:
      print("Parabéns você está bem remunerado!!!")