# -*- coding: utf-8 -*-
"""aula-03-iagen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxHb2xdikke8Ob8GNb99RrTdTb1kn48v
"""

lista_prompts = [
    "Um gato astronauta em marte",
    "ex 02",
    "ex 03",
    "ex 04",
    "exemplo 05"
]
print("...Iniciando a geração em lote de imagens...\n")

for prompt_atual in lista_prompts:
  print(f"Enviando para IA: {prompt_atual}")
  print("Gerando a imagem...[Concluido com sucesso]")

print("Todos os prints foram processados")

print("Contagem de número pares")

cont = 0

for i in range(21):
  if (i % 2 != 0):
    print(i)
  else:
    print(f"{i} é um número par")
    cont += 1
print(f"O número de números pares é {cont}")

c = False

while c == False:
  prompt = str(input("Digite seu prompt: "))
  if len(prompt) < 10:
    print("Prompt muito curto para executar")
  else:
    c = True
    print("Prompt aceito com sucesso!!!")