# -*- coding: utf-8 -*-
"""aula_05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XE2Xlqx5JpbO0K8xEjouCe7MCumIvrzT

Introdução ao Machine Learning
-

- É uma subarea da inteligência artificial que dá aos computadores a habilidade de aprender e melhorar a partir de experiência (dados), sem serem explicitamente programados.

- Oferecemos os dados e as respostas (padrões). O computador vai aprender qual é a refra do negocio.

Vocabulários:
-

- Dataset -> Conjunto de dados
- Features -> Caracteristicas/Atributos
- Label -> Rótulos/Respostas

Modelos de Aprendizado:
-

- Aprendizado supervisionado: Quando nós oferecemos as features junto com as respostas corretas para que o modelo treine:

-> Classificação

-> Regreção

- Aprendizado não supervisionado: Nós oferecemos dados porém não damos as respostas. O computador vai aprender por similaridade.
"""

x = 10
y = 20

print(f"A soma de de {x} + {y} é: {x + y}")

"""Prática
-

Classificação Simples com Scikit Learn

Cenário: Queremos prever se uma fruta é uma mação ou uma laranha com base um duas caracteristicas (features): Peso(gramas) e Textura(1 - lisa e 0 - irregular)
"""

from sklearn.tree import DecisionTreeClassifier

features = [
    [140, 1], #Fruta 1: 140g, lisa
    [130, 1], #Fruta 1: 130g, lisa
    [150, 0], #Fruta 1: 150g, Irregular
    [170, 0], #Fruta 1: 170g, Irregular
    [180, 1],
    [200, 0],
    [210, 1],
    [220, 0],
    [230, 1],
    [90, 1],
    [110, 0],
    [120, 1]
]
#0 = Maçã, 1 = Laranja
Labels = [0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0]

modelo = DecisionTreeClassifier()
modelo.fit(features, Labels)

fruta_nova = [[150, 1]] # Changed from [150, 1] to [[150, 1]]
previsao = modelo.predict(fruta_nova)

if previsao[0] == 0:
    print("A ia previo que a fruta é: Maçã")
else:
    print("A ia previo que a fruta é: Laranja")